### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jackpf** [jackpf/Kitchen-Sync#1]
- [ ] Icon
- [x] Refactor CInterface
- [x] Unique tmp & tmp2 names
- [ ] Removing doesnt cancel thread
- [x] Proper folder select
- [ ] Save previously entered target bpm
- [x] Proper checking in hasNativeDecoder()
- [ ] FLAC/WAV native writing with type select
- [x] MP3 decoder
- [x] AIF support?
- [ ] Only use ffmpeg when native decoders not present
- [ ] 24-bit FLAC buggy
- [ ] MP3 decoding buggy for some files
- [ ] Spectral analysis buggy
